amani/modules/features/amani_features/amani_global/amani_global.context.inc
amani/modules/features/amani_features/amani_global/amani_global.info
amani/modules/features/amani_features/amani_global/amani_global.install

- Added the 3 blocks on the content region on the homepage

Add the 3 blocks for the frontpage box content types

---

amani/themes/amani_zen/templates/view_slideshow/views-view-fields--front-page-slideshow--block.tpl.php

Added wrapper to wrap button, title & body for themeing.

added wrapper for button, title & body.

---

amani/modules/custom/amani_adminstrator/amani_administrator.admin.inc

Rename 'Manage Donate Button' to ''Manage Floating Button'

Rename 'Manage Donate Button' to Manage Floating Butto

---

amani/modules/features/amani_features/amani_front_page/amani_front_page.install

Updated value in hook_update, for amani:front page feature

updated value in hook_update, for footer img blocks to display

---

amani/modules/features/amani_features/amani_global/amani_global.context.inc

Added slideshow in subheader region.

Added slidhow in subheader region

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_front-page-blocks.scss
amani/themes/amani_zen/sass/theme/_layout.scss

tweaked on home page

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_misc.scss

add tagline theme

---

amani/modules/custom/amani_adminstrator/amani_administrator.admin.inc

- Added an item to "configure Amani" in order to choose the content type that will be used on the front page feed

Add menu item to configure content type to display on homepage feed

---

amani/modules/custom/amani_adminstrator/amani_administrator.admin.inc

- Update the description to add new visible content types on the front page

Add description to update content type for front page feed

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_front-page-blocks.scss
amani/themes/amani_zen/sass/components/_header.scss
amani/themes/amani_zen/sass/theme/_layout.scss

mobile theming

---

amani/modules/custom/amani_sms/amani_sms.info
amani/modules/custom/amani_sms/amani_sms.module

Add sms module

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_program_page.scss

program page preview body line-height reduced

---

amani/modules/features/amani_features/amani_about/amani_about.info
amani/modules/features/amani_features/amani_front_page/amani_front_page.context.inc
amani/modules/features/amani_features/amani_front_page/amani_front_page.info
amani/modules/features/amani_features/amani_front_page/amani_front_page.views_default.inc
amani/modules/features/amani_features/amani_global/amani_global.context.inc
amani/modules/features/amani_features/amani_global/amani_global.features.block_access.inc
amani/modules/features/amani_features/amani_global/amani_global.info
amani/modules/features/amani_features/amani_programs_campaigns/amani_programs_campaigns.info
amani/modules/features/amani_features/amani_programs_campaigns/amani_programs_campaigns.views_default.inc

- Make sure that the button "Bck to node" is on activity nodes

Show back button on activities node

---

amani/modules/features/amani_features/amani_resource/amani_resource.info
amani/modules/features/amani_features/amani_resource/amani_resource.install
amani/modules/features/amani_features/amani_resource/amani_resource.views_default.inc

This closes bug #1032, ready for Front End.
- Removed Keyword search
- Re-arranged fields
- Created .install file, updated and reverted feature.
*Ready for Front End changes.

Fixed filter options as per comment. Featured and reverted.

---

amani/modules/features/amani_features/amani_global/amani_global.features.user_permission.inc
amani/modules/features/amani_features/amani_global/amani_global.info

- Add administer views permission to amani admins

Add the administer views permission for amani admin

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_resources_page.scss

Add "Key word" search filter on side bar

Add "Key word" search filter on side bar

---

amani/modules/features/amani_features/amani_resource/amani_resource.features.field.inc
amani/modules/features/amani_features/amani_resource/amani_resource.info
amani/modules/features/amani_features/amani_resource/amani_resource.install
amani/modules/features/amani_features/amani_resource/amani_resource.views_default.inc
amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_resources_page.scss

The ticket related to this merge request, https://github.com/PeaceGeeksSociety/amani/issues/1092, wants some more to be done, but waiting on a designer to create a new UI for the full implementation/completion. However, the fact that the blocks are uneven was the most pressing issue, so added some style to fix that for now.

Amani-Zen-Theme: Made blocks smaller and uniform

---

amani/modules/custom/amani_adminstrator/amani_administrator.admin.inc
amani/modules/custom/amani_adminstrator/amani_administrator.module

This is related to issue: https://github.com/PeaceGeeksSociety/amani/issues/1100
This was attempted previously, but after further investigation, realized my implementation did not follow the same convention as the other amani configurations. Made changes so that it now does.

Amani-Zen-Theme: Admin Comment Enable/Disable

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_calendar.scss
amani/themes/amani_zen/template.php

The pull request is related to two issues:
- https://github.com/PeaceGeeksSociety/amani/issues/987
- https://github.com/PeaceGeeksSociety/amani/issues/1111

Amani-Zen-Theme: Calendar Views Issues 1111

---

amani/modules/features/amani_features/amani_article/amani_article.context.inc
amani/modules/features/amani_features/amani_article/amani_article.info
amani/modules/features/amani_features/amani_programs_campaigns/amani_programs_campaigns.info
amani/modules/features/amani_features/amani_programs_campaigns/amani_programs_campaigns.views_default.inc
amani/themes/amani_zen/template.php

This is related to issue: https://github.com/PeaceGeeksSociety/amani/issues/959.
Made the sidebar show Articles instead of Programs, met a few other issues while doing that, and resolved them too.

Amani Zen Theme: Article News Node Page Theme Issues

---

amani/modules/features/amani_features/amani_front_page/amani_front_page.info
amani/modules/features/amani_features/amani_front_page/amani_front_page.views_default.inc

This is related to the issue https://github.com/PeaceGeeksSociety/amani/issues/1068.
Added slight changes to the view so that the images link as well as the 'Read More' link.

Amani Zen Theme: Front Page Blocks Image Linking

---

amani/modules/custom/amani_adminstrator/amani_administrator.admin.inc
amani/modules/custom/amani_adminstrator/amani_administrator.module
amani/modules/features/amani_features/amani_block_and_views/amani_block_and_views.info
amani/modules/features/amani_features/amani_block_and_views/amani_block_and_views.views_default.inc
amani/modules/features/amani_features/amani_global/amani_global.context.inc
amani/modules/features/amani_features/amani_global/amani_global.info
amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_front-page-blocks.scss

This is related to issue https://github.com/PeaceGeeksSociety/amani/issues/1090.
Built this so there are multiple displays for the view, and then the Amani Admin can enable/disable any/all of them using the Config Amani interface.

Amani Zen Theme: Multiple Feeds Front Page

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_partners_page.scss
amani/themes/amani_zen/template.php
amani/themes/amani_zen/templates/node--partner.tpl.php

This is related to issue https://github.com/PeaceGeeksSociety/amani/issues/992.
Made some small changes to make the partner node match the mock design.

Amani Zen Theme: Partner Node Theme

---

amani/modules/features/amani_features/amani_programs_campaigns/amani_programs_campaigns.info
amani/modules/features/amani_features/amani_programs_campaigns/amani_programs_campaigns.views_default.inc

https://github.com/PeaceGeeksSociety/amani/issues/959

Amani Zen Theme: News Sidebar

---

amani/modules/custom/amani_adminstrator/amani_administrator.admin.inc
amani/modules/custom/amani_adminstrator/amani_administrator.module

https://github.com/PeaceGeeksSociety/amani/issues/1079

Amani Zen Theme: Partners Carousle Enable/Disable

---

amani/modules/contrib/date/date_views/includes/date_views_plugin_pager.inc
patches/calendar_pager_broken_2375235-35.patch

https://github.com/PeaceGeeksSociety/amani/issues/1039

Amani Zen Theme: Calendar Skipping Months

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_team_page.scss
amani/themes/amani_zen/templates/node--team.tpl.php

https://github.com/PeaceGeeksSociety/amani/issues/1022

Amani Zen Theme: Team Node Theme

---

amani/modules/features/amani_features/amani_global/amani_global.module

https://github.com/PeaceGeeksSociety/amani/issues/1131

Amani Zen Theme: Logo Upload Not Working Fixed

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_team_page.scss
amani/themes/amani_zen/template.php
amani/themes/amani_zen/templates/node--team.tpl.php

https://github.com/PeaceGeeksSociety/amani/issues/1022

Amani Zen Theme: Team Node Theme Fix

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_footer.scss
amani/themes/amani_zen/sass/components/_menus.scss

This merge request is related to these issues:
* https://github.com/PeaceGeeksSociety/amani/issues/1119
* https://github.com/PeaceGeeksSociety/amani/issues/1123

Amani Zen Theme: Social Media Header/Footer Icons

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_menus.scss

https://github.com/PeaceGeeksSociety/amani/issues/1123

Fixed css for social media images overlapping search box

---

amani/modules/features/amani_features/amani_partners/amani_partners.features.field.inc
amani/modules/features/amani_features/amani_partners/amani_partners.info
amani/modules/features/amani_features/amani_partners/amani_partners.strongarm.inc
amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_partners_page.scss
amani/themes/amani_zen/templates/node--partner.tpl.php

https://github.com/PeaceGeeksSociety/amani/issues/992

Showing the Map record and website link as well now

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/_init.scss
amani/themes/amani_zen/sass/components/_footer.scss
amani/themes/amani_zen/sass/components/_menus.scss

https://github.com/PeaceGeeksSociety/amani/issues/1119

Adding fonts and icons to social media

---

amani/themes/amani_zen/css/styles.css
amani/themes/amani_zen/sass/components/_front-page-blocks.scss

https://github.com/PeaceGeeksSociety/amani/issues/1144

Removed css that made the frame/shadow show up

---

amani/modules/custom/amani_adminstrator/amani_administrator.admin.inc
amani/modules/custom/amani_adminstrator/amani_administrator.module

https://github.com/PeaceGeeksSociety/amani/issues/1141

Added ability to choose title to amani config page

---

amani/modules/custom/amani_adminstrator/amani_administrator.admin.inc
amani/modules/custom/amani_adminstrator/amani_administrator.module

https://github.com/PeaceGeeksSociety/amani/issues/1142

Added config section for re-ording front page feeds

---

amani/modules/features/amani_features/amani_global/amani_global.context.inc
amani/modules/features/amani_features/amani_global/amani_global.info

export logo beans of footer
